version: 0.12.1.{build}
environment:
  TOKEN:
    secure: KE3DuBSMhbBxLurkOXLrmAFbF+zptuCJztv1LDq1DfU65A1NSoYTI9JpYE63h/66

build_script:
  - ps: choco pack

test_script:
  - ps: .\test.ps1 -cpu x64
  - ps: .\test.ps1 -cpu x86

deploy_script:
  - ps: >-
      Write-Host $env:APPVEYOR_REPO_TAG ;
      if($env:APPVEYOR_REPO_BRANCH -eq 'master' -And $env:APPVEYOR_REPO_TAG -eq 'true') {
        $version = $env:APPVEYOR_BUILD_VERSION -replace('\.[^.\\/]+$') ;
        choco apiKey -k $env:TOKEN -source https://chocolatey.org/ ;
        choco push packer.$version.nupkg
      }

artifacts:
  - path: '**\*.nupkg'
    name: Package
